### ISSUE TITLE
Tab key markup doesn't display tab symbol

### ISSUE THREAD

**Issue by gcapes** [carpentries/lesson-example#246]
http://carpentries.github.io/lesson-example/06-style-guide/index.html#keyboard-key-combination

The tab key is rendered as a key with the word 'Tab' on it. More than half the keyboards in my office only have the arrow symbols on them without the word, so the key representation in our lessons wouldn't make it any easier to identify.

Would it be possible to have something like this as the representation?
![image](https://user-images.githubusercontent.com/12446270/50765450-dd986c80-126d-11e9-991d-0c0a715e9174.png)

**Comment by rgaiacs** [comment]
@gcapes Thanks for the issue. We could use `<kbd>Tab ↹</kbd>` but if we do it we will need to review the Backspace, Return and Shift. I don't want to review the keys because every keyboard use one different representation, e.g. my keyboard doesn't have the word "Return". Not include the `↹` symbol will make easier to write the lesson and make our style uniform. Thanks again for the issue. I'm keeping the issue open for a few more days to see what other people think.

**Comment by gcapes** [comment]
Yep, OK fair enough.

**Comment by maxim-belkin** [comment]
My preference would be to keep names only unless we make similar changes to all of the keys. But then the question is if it would make it better or not, because it has to be rendered "inline", so the text on the key will be smaller than the regular text.

**Comment by gcapes** [comment]
Happy for the issue to be closed, or the discussion to continue - you've both made good arguments to close the issue with no changes.
