### ISSUE TITLE
"weekly styles update" notification

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/lesson-example#357]
I now receive weekly "Weekly Styles Update: All jobs have failed" notifications from my fork of this lesson. I think this is something we need to address before using the same GH action in other repositories.

CC @zkamvar.

**Comment by zkamvar** [comment]
Oh snap. I fixed this in other test lessons, but I never addressed this in the lesson example.

The solution I came up with was to validate the token. Here's an example from an incubator lesson: https://github.com/carpentries-incubator/git-novice-branch-pr/blob/gh-pages/.github/workflows/update-styles.yml

I'll make a PR to fix this so that you don't get notified. I'll also make it so that it only runs on carpentries/lesson-example

**Comment by zkamvar** [comment]
Also: I'm sorry for the mess of notifications. I'll try to be better about that in the future.
